{% set name = "dart-sdk" %}
{% set version = "2.17.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-macos-x64-release.zip  # [osx and x86_64]
    sha256: ba258fff40822cb410c4f1f7916b63f0837903a6bae8f4bd83341053b10ecbe3  # [osx and x86_64]
  - url: https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-macos-arm64-release.zip  # [osx and arm64]
    sha256: a4be379202cf731c7e33de20b4abc4ca1e2e726bc5973222b3a7ae5a0cabfce1  # [osx and arm64]
  - url: https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-linux-x64-release.zip  # [linux and x86_64]
    sha256: ba8bc85883e38709351f78c527cbf72e22cd234b3678a1ec6a2e781f7984e624  # [linux and x86_64]
  - url: https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-linux-arm64-release.zip  # [linux and aarch64]
    sha256: ee0acf66e184629b69943e9f29459e586095895c6aae6677ab027d99c00934b6  # [linux and aarch64]
  - url: https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-windows-x64-release.zip  # [win]
    sha256: 572ed6e5e8f101304f9f152cd77fdb9736a5f859ec9f609b5d5f1647b1dc75b2  # [win]

build:
  # There are no binaries available for ppc64le, so we can't repack anything
  # https://dart.dev/get-dart/archive
  skip: true  # [ppc64le]
  number: 0
  binary_relocation: false
  missing_dso_whitelist:
    # normal linux stuff that would go away if we had libgcc-ng in the run deps
    - '*/ld-linux.so.2'
    - '*/lib64/ld-linux-x86-64.so.2'
    - '*/libpthread.so.0'
    - '*/libdl.so.2'
    - '*/libm.so.6'
    - '*/libc.so.6'

test:
  commands:
    - dart --help
    - IF NOT EXIST "%LIBRARY_BIN%\dart.exe" exit 1   # [win]

about:
  home: https://dart.dev/
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: a client-optimized language for developing fast apps on any platform

extra:
  recipe-maintainers:
    - msarahan
