{% set name = "dart-sdk" %}
{% set version = "2.19.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-macos-x64-release.zip  # [osx and x86_64]
    sha256: 07136127f4f1fc8ff54ab3d69df53535bed14027d56982c0db4af394ed8d0c25  # [osx and x86_64]
  - url: https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-macos-arm64-release.zip  # [osx and arm64]
    sha256: 612118e856e6eedbdbea4c8d9e6cd1fa73a21614db7ed2e66dd991901004a103  # [osx and arm64]
  - url: https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-linux-x64-release.zip  # [linux and x86_64]
    sha256: f8591944512834ba19b4d8383d270d7f56fef03c56ba53d4e35c23db80ea8a33  # [linux and x86_64]
  - url: https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-linux-arm64-release.zip  # [linux and aarch64]
    sha256: c81303feea24228148bd4ec14c65bb9c341cba3596e3d68e8a874a9df947f928  # [linux and aarch64]
  - url: https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-windows-x64-release.zip  # [win]
    sha256: 852cb28d274603b5c4940a1710a49bdc2535b7f726645b3baed9bc97bd1ec45f  # [win]

build:
  # There are no binaries available for ppc64le, so we can't repack anything
  # https://dart.dev/get-dart/archive
  skip: true  # [ppc64le]
  number: 0
  binary_relocation: false
  missing_dso_whitelist:
    # normal linux stuff that would go away if we had libgcc-ng in the run deps
    - '*/ld-linux.so.2'
    - '*/lib64/ld-linux-x86-64.so.2'
    - '*/libpthread.so.0'
    - '*/libdl.so.2'
    - '*/libm.so.6'
    - '*/libc.so.6'

test:
  commands:
    - dart --help
    - IF NOT EXIST "%LIBRARY_BIN%\dart.exe" exit 1   # [win]

about:
  home: https://dart.dev/
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: a client-optimized language for developing fast apps on any platform

extra:
  recipe-maintainers:
    - msarahan
