context:
  version: "3.13.0"

package:
  name: dart-sdk
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-linux-x64-release.zip
      sha256: 87902573facd8acacac7ee1fe73fa8d0668e06065016068e2ed6c5c99c6b1ee0
  - if: linux and aarch64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-linux-arm64-release.zip
      sha256: 20141a0653327939bb20c4b87b231226beba1128d8a9aedbb30cb5af1a2790d4
  - if: win and x86_64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-windows-x64-release.zip
      sha256: 8480a527e621e9b06f1121cb4f56204e5c2b07851021cbe63965399de4d7f407
  - if: osx and x86_64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-macos-x64-release.zip
      sha256: 6f75f0d6bc10c00457fb5b8861b26eadc5d883cfd11aa26a8c4f6353af370f47
  - if: osx and arm64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-macos-arm64-release.zip
      sha256: 1812d602aed0a9cf7281c93f514a1e1aecf60dc345c4337dba4ff28fa8d398ca

build:
  number: 0
  skip:
    - ppc64le
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      # normal linux stuff that would go away if we had libgcc-ng in the run deps
      - "*/ld-linux.so.2"
      - "*/lib64/ld-linux-x86-64.so.2"
      - "*/libpthread.so.0"
      - "*/libdl.so.2"
      - "*/libm.so.6"
      - "*/libc.so.6"

tests:
  - package_contents:
      bin:
        - if: win
          then: dart.exe
  - script:
      - dart --help

about:
  homepage: https://dart.dev/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: a client-optimized language for developing fast apps on any platform
  repository: https://github.com/dart-lang/sdk
  documentation: https://dart.dev/

extra:
  recipe-maintainers:
    - msarahan
    - munechika-koyo
