context:
  version: "3.11.3"

package:
  name: dart-sdk
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-linux-x64-release.zip
      sha256: 119f4d0d51b3697e8435a2aaa19d58727c1b92f00e7e8084ba3539cb3fc65fac
  - if: linux and aarch64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-linux-arm64-release.zip
      sha256: 69edeb88a9adebd64019cbec13285433943f0f24aa79d9d108fdcd69fc84ac2e
  - if: win and x86_64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-windows-x64-release.zip
      sha256: 97bcaf959771b29be94f352ce453e24c4e60b9368fe5e9803052ecacaff1dea1
  - if: osx and x86_64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-macos-x64-release.zip
      sha256: 27b5ecf74973520627c217bb0e9b1dcc0dd531eddeb8cca577bf152096a7e7ed
  - if: osx and arm64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-macos-arm64-release.zip
      sha256: d6ea15796e7976636b361bb935054934fcba3d05edfae8a4ec7bf39d43dbbcd6

build:
  number: 0
  skip:
    - ppc64le
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      # normal linux stuff that would go away if we had libgcc-ng in the run deps
      - "*/ld-linux.so.2"
      - "*/lib64/ld-linux-x86-64.so.2"
      - "*/libpthread.so.0"
      - "*/libdl.so.2"
      - "*/libm.so.6"
      - "*/libc.so.6"

tests:
  - package_contents:
      bin:
        - if: win
          then: dart.exe
  - script:
      - dart --help

about:
  homepage: https://dart.dev/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: a client-optimized language for developing fast apps on any platform
  repository: https://github.com/dart-lang/sdk
  documentation: https://dart.dev/

extra:
  recipe-maintainers:
    - msarahan
    - munechika-koyo
