context:
  version: "3.12.2"

package:
  name: dart-sdk
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-linux-x64-release.zip
      sha256: 28e47b44cf075f36771046c068bb0d174201cf9c7608744aed1cc23204299c2d
  - if: linux and aarch64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-linux-arm64-release.zip
      sha256: f82c83ece7d168047550dfd4a664e4071ac7c488bddb72dc43102c22d7e0b518
  - if: win and x86_64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-windows-x64-release.zip
      sha256: 77fd96c823ed09a85e58209a2c5f16b0fc02e5ed4f3e3d46fddf4be763d498d6
  - if: osx and x86_64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-macos-x64-release.zip
      sha256: 38199f56fe22f2235e76799191d5b9516e360369c61b6ba4411398d5d5920bab
  - if: osx and arm64
    then:
      url: https://storage.googleapis.com/dart-archive/channels/stable/release/${{ version }}/sdk/dartsdk-macos-arm64-release.zip
      sha256: cd8753928e77b6b665bd70dce0e64b4ec6d2e2fde141d6409bb716c8ac1f1c0a

build:
  number: 0
  skip:
    - ppc64le
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      # normal linux stuff that would go away if we had libgcc-ng in the run deps
      - "*/ld-linux.so.2"
      - "*/lib64/ld-linux-x86-64.so.2"
      - "*/libpthread.so.0"
      - "*/libdl.so.2"
      - "*/libm.so.6"
      - "*/libc.so.6"

tests:
  - package_contents:
      bin:
        - if: win
          then: dart.exe
  - script:
      - dart --help

about:
  homepage: https://dart.dev/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: a client-optimized language for developing fast apps on any platform
  repository: https://github.com/dart-lang/sdk
  documentation: https://dart.dev/

extra:
  recipe-maintainers:
    - msarahan
    - munechika-koyo
